[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
family = "CommitMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CommitMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CommitMono Nerd Font"
style = "Italic"

[font.normal]
family = "CommitMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "None"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "W"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleSimpleFullscreen"
key = "F"
mods = "Command|Control"

[scrolling]
history = 100000

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "none"
opacity = 0.85
blur = true

[window.padding]
x = 2
y = 2

[general]
live_config_reload = true
import = ["~/.config/alacritty/themes/gruvbox_material_hard_light.toml"]
