require('dimzst.config.registers')
require('dimzst.config.telescope')
require('dimzst.config.dressing')
require('dimzst.config.treesitter')
require('dimzst.config.snippet')
require('dimzst.config.cmp')
require('dimzst.config.lsp')
require('dimzst.config.colorscheme')
require('dimzst.config.lualine')
require('dimzst.config.gitsigns')
require('dimzst.config.rest')
require('dimzst.config.nvimtree')
require('dimzst.config.focus')
require('dimzst.config.lint')
require('dimzst.config.comment')
require('dimzst.config.quickfix')
require('dimzst.config.diagnostic')
-- require('dimzst.config.ui')
