#!/usr/bin/env bash

set -eo pipefail

REPO_GIT="$1"
REPO_DIR="$(echo $REPO_GIT | awk -F/ '{print $NF}' | cut -d. -f1)"
if [ ! -z "$2" ]; then
    REPO_DIR="$2"
fi

git clone --bare $REPO_GIT $REPO_DIR

cd $REPO_DIR

git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
git fetch origin
