#!/usr/bin/env bash

set -eo pipefail

FZF_OPT="-p --layout reverse"

TO_BE_REMOVE="$(git worktree list --porcelain | grep ^worktree | tail -n +2 | awk '{print $2}' | xargs -n 1 basename | fzf-tmux $FZF_OPT --prompt=remove:)"
GIT_WORKTREE_OPTS="$@"

if [ -z "$TO_BE_REMOVE" ]; then
	echo "worktree to be remove is required" 1>&2;
	exit 1;
fi

BRANCH="$(git worktree list | grep $TO_BE_REMOVE | awk '{print $3}' | tr -d \[\])"
if [ "$BRANCH" == "" ]; then
	echo "could not identify worktree branch" 1>&2;
	exit 1;
fi

git worktree remove $TO_BE_REMOVE $GIT_WORKTREE_OPTS
git branch -D $BRANCH
