#!/usr/bin/env bash

ALACRITTY_CONFIG_DIR="$HOME/.config/alacritty"
ALACRITTY_CONFIG_FILENAME="alacritty.toml"
ALACRITTY_CONFIG_FILE="$ALACRITTY_CONFIG_DIR/$ALACRITTY_CONFIG_FILENAME"
NVIM_CONFIG_DIR="$HOME/.config/nvim"
NVIM_CONFIG_FILE="init.vim"
USQL_CONFIG_FILE="$HOME/.usqlrc"
CHT_CONFIG_DIR="$HOME/.cht.sh"
CHT_CONFIG_FILENAME="cht.sh.conf"
CHT_CONFIG_FILE="$CHT_CONFIG_DIR/$CHT_CONFIG_FILENAME"

THEME="dark"
if [ -n "$1" ]; then
	THEME=$1
fi

export TERM_THEME=$THEME

switch-alactritty() {
	if [ ! -f "$ALACRITTY_CONFIG_FILE" ]; then
		echo "$ALACRITTY_CONFIG_FILE not found" 1>&2;
		exit 1
	fi

	theme=$1
	if [ "$theme" = "dark" ]; then
		alacritty_theme="gruvbox_material_medium_dark"
	else
		alacritty_theme="gruvbox_material_hard_light"
	fi

	REAL_CONFIG="$(readlink $ALACRITTY_CONFIG_DIR)/$ALACRITTY_CONFIG_FILENAME"

	gsed -i -e "s#/alacritty/themes/*.*\.toml#/alacritty/themes/$alacritty_theme\.toml#g" $REAL_CONFIG
}

switch-tmux() {
	theme=$1
	if [ "$theme" = "dark" ]; then
		tmux source-file ~/.config/tmux/tmux-dark.conf
	else
		tmux source-file ~/.config/tmux/tmux-light.conf
	fi
}

switch-nvim() {
	theme=$1

    REAL_DIR="$(readlink $NVIM_CONFIG_DIR)"

	REAL_CONFIG="$REAL_DIR/$NVIM_CONFIG_FILE"
	if [ ! -f "$REAL_CONFIG" ]; then
		echo "nvim config file not found" 1>&2;
		exit 1
	fi

	gsed -i -e "s#^set background=*.*#set background=$theme#g" $REAL_CONFIG

	COLORSCHEME_FILE="$REAL_DIR/lua/dimzst/config/colorscheme.lua"
    BACKGROUND="medium"
	theme=$1
	if [ "$theme" = "light" ]; then
        BACKGROUND="hard"
	fi
	gsed -i -e "s#^vim\.g\[\"gruvbox_material_background\"\]*.*#vim\.g\[\"gruvbox_material_background\"] = '$BACKGROUND'#g" $COLORSCHEME_FILE

	is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
		| grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"

	for pane in $(tmux lsp -a -F "#{session_name}:#{window_index}.#{pane_index}"); do
		tmux if-shell -t "$pane" "$is_vim" "send-keys -t $pane escape ENTER"
		tmux if-shell -t "$pane" "$is_vim" "send-keys -t $pane ';ChangeTheme $theme' ENTER"
	done
}

switch-usql() {
	if [ ! -f "$USQL_CONFIG_FILE" ]; then
		echo "$USQL_CONFIG_FILE not found" 1>&2;
		exit 1
	fi

	theme=$1
	if [ "$theme" = "dark" ]; then
		usql_theme="gruvbox"
	else
		usql_theme="gruvbox-light"
	fi

	REAL_CONFIG="$(readlink $USQL_CONFIG_FILE)"

	gsed -i -e "s#^\\\set SYNTAX_HL_STYLE *.*#\\\set SYNTAX_HL_STYLE $usql_theme#g" $REAL_CONFIG
}

switch-cht() {
	if [ ! -f "$CHT_CONFIG_FILE" ]; then
		echo "$CHT_CONFIG_FILE not found" 1>&2;
		exit 1
	fi

	theme=$1
	if [ "$theme" = "dark" ]; then
		theme="paraiso-dark"
	else
		theme="paraiso-light"
	fi

	REAL_CONFIG="$(readlink $CHT_CONFIG_DIR)/$CHT_CONFIG_FILENAME"

	gsed -i -e "s#^CHTSH_QUERY_OPTIONS=*.*#CHTSH_QUERY_OPTIONS=\"style=$theme\"#g" $REAL_CONFIG
}

switch-alactritty $THEME
switch-tmux $THEME
switch-nvim $THEME
switch-usql $THEME
switch-cht $THEME
